version: "3.8"
services:
  nginx:
    image: nginx:1.19.3
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./src:/usr/share/nginx/html
    ports:
    - 8000:80
    links:
    - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
    - ./src:/usr/share/nginx/html 
